"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import "./admin.css";
const blank=()=>({slug:"",title:"",date:new Date().toISOString().slice(0,10),location:"",image:"",excerpt:"",content:""});
export default function Admin(){
 const [ok,setOk]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[posts,setPosts]=useState([]),[post,setPost]=useState(blank()),[error,setError]=useState(""),[status,setStatus]=useState("");
 async function load(){const r=await fetch("/api/admin/posts",{cache:"no-store"});if(!r.ok){setOk(false);return}setPosts((await r.json()).posts||[]);setOk(true)} useEffect(()=>{load()},[]);
 async function login(e){e.preventDefault();setError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});if(!r.ok){setError((await r.json()).error);return}await load()}
 async function save(e){e.preventDefault();setError("");setStatus("Speichere …");const r=await fetch("/api/admin/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(post)});const d=await r.json();if(!r.ok){setError(d.error);setStatus("");return}setStatus("Gespeichert – Vercel veröffentlicht automatisch.");await load()}
 async function del(){if(!confirm("Beitrag wirklich löschen?"))return;const r=await fetch("/api/admin/posts",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({slug:post.slug})});if(!r.ok){setError((await r.json()).error);return}setPost(blank());await load()}
 async function upload(e){const f=e.target.files?.[0];if(!f)return;if(f.size>9*1024*1024){setError("Maximal 9 MB.");return}const reader=new FileReader();reader.onload=async()=>{setStatus("Bild wird hochgeladen …");const r=await fetch("/api/admin/upload",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:f.name,data:reader.result})});const d=await r.json();if(!r.ok)setError(d.error);else{setPost(p=>({...p,image:d.url}));setStatus("Bild hochgeladen – jetzt speichern.")}};reader.readAsDataURL(f)}
 if(ok===null)return <div className="admin-loading">Lepigonia Admin …</div>;
 if(!ok)return <main className="admin-login"><Link href="/" className="admin-brand">Lepigonia</Link><div className="login-card"><p className="admin-eyebrow">Private area</p><h1>Admin Login</h1><p>Geschichten und Bilder direkt auf der Website verwalten.</p><form onSubmit={login}><label>E-Mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Passwort<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button>Einloggen →</button>{error&&<p className="admin-error">{error}</p>}</form></div></main>;
 return <main className="admin-shell"><header className="admin-top"><div><Link href="/" className="admin-brand">Lepigonia</Link><span> / Admin</span></div><div><Link href="/" target="_blank">Website ↗</Link><button onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});setOk(false)}}>Logout</button></div></header><div className="admin-grid"><aside className="admin-sidebar"><b>Stories</b><button className="new-button" onClick={()=>{setPost(blank());setError("")}}>＋ Neue Geschichte</button>{posts.map(p=><button key={p.slug} className={`post-nav ${post.slug===p.slug?"active":""}`} onClick={()=>setPost(p)}><strong>{p.title||p.slug}</strong><small>{p.location||"Ohne Ort"}</small></button>)}</aside><section className="editor"><div className="editor-head"><div><p className="admin-eyebrow">Editor</p><h1>{post.slug?"Geschichte bearbeiten":"Neue Geschichte"}</h1></div>{post.slug&&<button className="danger" onClick={del}>Löschen</button>}</div><form onSubmit={save} className="editor-form"><div className="field-row"><label>Titel<input value={post.title} onChange={e=>setPost({...post,title:e.target.value})} required/></label><label>Slug<input value={post.slug} onChange={e=>setPost({...post,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-")})} required/></label></div><div className="field-row"><label>Datum<input type="date" value={post.date} onChange={e=>setPost({...post,date:e.target.value})}/></label><label>Ort<input value={post.location} onChange={e=>setPost({...post,location:e.target.value})}/></label></div><label>Teaser<input value={post.excerpt} onChange={e=>setPost({...post,excerpt:e.target.value})}/></label><label>Bild-URL<input value={post.image} onChange={e=>setPost({...post,image:e.target.value})} placeholder="/uploads/dein-bild.webp"/></label><label className="upload">Bild hochladen<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload}/></label><label>Text (Markdown)<textarea className="content-editor" value={post.content} onChange={e=>setPost({...post,content:e.target.value})}/></label><div className="save-row"><button className="save">Speichern & veröffentlichen →</button>{status&&<span className="status">{status}</span>}</div>{error&&<p className="admin-error">{error}</p>}</form></section></div></main>;
}
