import crypto from "node:crypto";
const COOKIE = "lepigonia_admin";
const getSecret = () => { if (!process.env.ADMIN_SESSION_SECRET) throw new Error("ADMIN_SESSION_SECRET is not configured"); return process.env.ADMIN_SESSION_SECRET; };
export function makeSession(email) { const payload = Buffer.from(JSON.stringify({ email, exp: Date.now() + 604800000 })).toString("base64url"); const sig = crypto.createHmac("sha256", getSecret()).update(payload).digest("base64url"); return `${payload}.${sig}`; }
export function verifySession(value) { try { if (!value) return false; const [payload, sig] = value.split("."); const expected = crypto.createHmac("sha256", getSecret()).update(payload).digest("base64url"); if (!sig || sig.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return false; const data = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")); return data.exp > Date.now() && data.email === process.env.ADMIN_EMAIL; } catch { return false; } }
export const isAdmin = (request) => verifySession(request.cookies.get(COOKIE)?.value);
export const setAdminCookie = (response, email) => response.cookies.set(COOKIE, makeSession(email), { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/", maxAge: 604800 });
export const clearAdminCookie = (response) => response.cookies.set(COOKIE, "", { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/", maxAge: 0 });
export function githubConfig() { if (!process.env.GITHUB_TOKEN) throw new Error("GITHUB_TOKEN is not configured"); return { token: process.env.GITHUB_TOKEN, owner: process.env.GITHUB_OWNER || "Lepigonia", repo: process.env.GITHUB_REPO || "Lepigonia", branch: process.env.GITHUB_BRANCH || "main" }; }
export async function githubRequest(path, options = {}) { const { token } = githubConfig(); const r = await fetch(`https://api.github.com${path}`, { ...options, headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "X-GitHub-Api-Version": "2022-11-28", ...(options.headers || {}) }, cache: "no-store" }); const text = await r.text(); let data; try { data = text ? JSON.parse(text) : null; } catch { data = { message: text }; } if (!r.ok) throw new Error(data?.message || `GitHub request failed (${r.status})`); return data; }
export async function getGithubFile(path) { const { owner, repo, branch } = githubConfig(); return githubRequest(`/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`); }
export async function putGithubFile(path, content, message, sha) { const { owner, repo, branch } = githubConfig(); const body = { message, content: Buffer.from(content, "utf8").toString("base64"), branch }; if (sha) body.sha = sha; return githubRequest(`/repos/${owner}/${repo}/contents/${path}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); }
export async function putGithubBinary(path, base64, message, sha) { const { owner, repo, branch } = githubConfig(); const body = { message, content: base64.replace(/^data:[^;]+;base64,/, ""), branch }; if (sha) body.sha = sha; return githubRequest(`/repos/${owner}/${repo}/contents/${path}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); }
export async function deleteGithubFile(path, message, sha) { const { owner, repo, branch } = githubConfig(); return githubRequest(`/repos/${owner}/${repo}/contents/${path}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, sha, branch }) }); }
